apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeepe
    pattern: zk-mpt
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: zookeeper
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata: 
  name: zookeeper
  labels:
    pattern: zk-mpt
spec: 
  replicas: 3
  serviceName: zookeeper
  template:
    metadata: 
      labels: 
        app: zookeeper
        pattern: zk-mpt
    spec:
      securityContext: 
        runAsUser: zk
        fsGroup: zk
      containers:
      - name: zookeeper
        image: "smartlab/zookeeper:3.4.11"
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        env:
        - name : ZK_REPLICAS
          value: "3"
        volumeMounts: 
        - mountPath: /zookeeper_data
          name: data
        - mountPath: /zookeeper_datalog
          name: datalog
        readinessProbe:
          exec:
            command:
            - bin/zookeeperOK.sh
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - bin/zookeeperOK.sh
          initialDelaySeconds: 10
          timeoutSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: 
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard
  - metadata:
      name: datalog
    spec:
      accessModes: 
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard
