apiVersion: v1
kind: StatefulSet
apiVersion: apps/v1beta1
metadata: 
  name: zookeeper
spec: 
  replicas: 3
  serviceName: zookeeper
  template:
    metadata: 
      labels: 
        app: zookeeper
    spec:
      securityContext: 
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: zookeeper
        image: "smartlab/zookeeper:3.4.12"
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 2181
          protocol: TCP
        - containerPort: 2888
          protocol: TCP
        - containerPort: 3888
          protocol: TCP
        env:
        - name : ZK_REPLICAS
          value: "3"
        volumeMounts: 
        - mountPath: /zk_data
          name: data
        - mountPath: /zk_datalog
          name: datalog
        readinessProbe:
          exec:
            command:
            - bin/zkOK.sh
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - bin/zkOK.sh
          initialDelaySeconds: 10
          timeoutSeconds: 5
      dnsPolicy: ClusterFirst 
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: 
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard
  - metadata:
      name: datalog
    spec:
      accessModes: 
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard
