apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    name: zookeeper
spec:
  type: NodePort
  ports:
    - port: 2181
      nodePort: 32181
      name: http
  selector:
    app: zookeeper
