apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-4
  labels:
    type: local
    pattern: zookeeper
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /var/exports/zookeeper/4
    server: 172.18.20.141 
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-5
  labels:
    type: local
    pattern: zookeeper
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /var/exports/zookeeper/5
    server: 172.18.20.141 
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-6
  labels:
    type: local
    pattern: zookeeper
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /var/exports/zookeeper/6
    server: 172.18.20.141 
  persistentVolumeReclaimPolicy: Recycle
